# Site settings
title: Philipp Nguyen - Aerospace Eng. PhD Student
description: Philipp Nguyen - Aerospace Eng. PhD Student
baseurl: "/PhilippNguyen.github.io" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Philipp Nguyen
user_description: I am a PhD student in Aerospace Engineering at the University of Manchester, UK. Previously, I graduated with Master degrees in Aerospace Engineering and Management from the Technical University of Munich, Germany, where I have been awarded Erasmus scholarships to write my Master's thesis at the University of Zurich, Switzerland, and to undertake an internship at Airbus in Toulouse, France.
user_title: PhD Student
email: philipp.nguyen@manchester.ac.uk
twitter_username: philippMUC
github_username:  PhilippNguyen
# gplus_username:  lorem_ipsum
# Google-analytics
google-analytics:
  id: "UA-125490535-1"

exclude: ['package.json', 'src' , 'node_modules']
